# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
  encoders:
    Symfony\Component\Security\Core\User\Users: plaintext
    OC\UserBundle\Entity\User: plaintext

  role_hierarchy:
    # Un admin hérite des droits d'auteur et de modérateur
    ROLE_ADMIN:       [ROLE_AUTEUR, ROLE_MODERATEUR]
    # On garde ce rôle super admin, il nous resservira par la suite
    ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

  # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
  providers:
    main:
      entity:
        class: OC\UserBundle\Entity\User
        property: username

  provider: in_memory
  firewalls:
    # disables authentication for assets and the profiler, adapt it according to your needs
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      pattern: ^/
      anonymous: true
      provider: main
      form_login:
        login_path: login
        check_path: login_check
      logout:
        path:   logout
        target: /platform

  access_control:
    #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
    - { path: ^/admin, roles: ROLE_ADMIN }